/**
 * Exported-spec executability check (reliability pass — "validate real
 * executability of exported tests").
 *
 * `compileCheck.ts` only proves a generated spec *parses* as TypeScript; it
 * never resolves Cypress's ambient types or proves a single generated line
 * actually runs. This test builds a representative flow through the same
 * `buildSpec` a real user's "Build Test" export goes through, then writes
 * the two resulting files into the real `cypress/` project (which already
 * has a real `cypress/tsconfig.json` with `"types": ["cypress"]`) instead of
 * a throwaway in-memory check.
 *
 * Two follow-on steps, run from `npm run verify:export`, do what this test
 * cannot do on its own:
 *   1. `tsc --noEmit -p cypress/tsconfig.json` — a real type-check against
 *      Cypress's actual ambient types (`cy`, `Cypress`, `describe`, `it`, ...).
 *   2. `cypress run --spec cypress/e2e/generated/exported-dashboard.cy.ts` —
 *      actually executes the generated spec, in a real browser, against the
 *      static `public/fixtures/app.html` target page, exercising a login,
 *      an intercepted network request consumed via a saved alias, a fixture
 *      load, and an invoked reusable-flow custom command.
 *
 * This test's own job is just step 0: generate deterministic, correct output
 * and write it to disk. `cypress/e2e/generated/` and
 * `cypress/support/generated-commands.ts` are gitignored build artifacts,
 * regenerated by this test every time `verify:export` runs.
 */

import { describe, expect, it } from 'vitest';
import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { buildSpec } from './buildSpec';
import { getDefaultReusableFlows } from '../config/reusableFlowsConfig';
import type { FlowNode } from '../domain/types';

const GENERATED_SPEC_PATH = join(
  __dirname,
  '../../cypress/e2e/generated/exported-dashboard.cy.ts',
);
const GENERATED_COMMANDS_PATH = join(
  __dirname,
  '../../cypress/support/generated-commands.ts',
);

/**
 * A flow exercising, in one tree, everything the review flagged as needing
 * real proof: a real DOM interaction (login), a chain (`intercept` + `as`),
 * an alias wait, a fixture load, and a reusable-flow invocation (which
 * exercises `generateReusableFlowCommand`, not just `processFlow`).
 */
export function exportedDashboardFlow(): FlowNode {
  return {
    id: 'root',
    type: 'describe',
    props: { label: 'Exported Dashboard Flow' },
    children: [
      {
        id: 'it-1',
        type: 'it',
        props: { label: 'logs in, saves, and logs out' },
        children: [
          { id: 'visit-1', type: 'visit', props: { url: '/fixtures/app.html' } },
          { id: 'type-user', type: 'type', props: { selector: '#username', value: 'tester' } },
          { id: 'type-pass', type: 'type', props: { selector: '#password', value: 'secret123' } },
          { id: 'click-login', type: 'click', props: { selector: '#login-submit' } },
          {
            id: 'assert-dashboard',
            type: 'should',
            props: { selector: '#dashboard', assertion: 'be.visible' },
          },
          {
            id: 'chain-intercept',
            type: 'chain',
            props: {},
            children: [
              {
                id: 'intercept-1',
                type: 'intercept',
                props: { method: 'POST', url: '/api/save' },
              },
              { id: 'as-1', type: 'as', props: { name: 'saveRequest' } },
            ],
          },
          { id: 'click-save', type: 'click', props: { selector: '#save-button' } },
          { id: 'wait-alias', type: 'waitAlias', props: { alias: '@saveRequest' } },
          {
            id: 'assert-notification',
            type: 'should',
            props: { selector: '#notification', assertion: 'contain.text', value: 'Saved' },
          },
          { id: 'fixture-1', type: 'fixture', props: { path: 'sample.json' } },
          { id: 'invoke-logout', type: 'flowInvocation', props: { flowId: 'logout' } },
        ],
      },
    ],
  };
}

describe('exported-spec executability fixture', () => {
  it('builds a self-contained spec + commands pair with no diagnostics', () => {
    const built = buildSpec(exportedDashboardFlow(), undefined, getDefaultReusableFlows());
    expect(built).not.toBeNull();
    expect(built!.usedFlowIds).toEqual(['logout']);
    expect(built!.fixturePaths).toEqual(['sample.json']);
    expect(built!.commandsCode).toContain("Cypress.Commands.add('logout'");
    expect(built!.commandTypesCode).toContain('logout(): Chainable<void>;');
    expect(built!.specCode).toContain('cy.logout();');
    expect(built!.specCode).toContain("cy.intercept('POST', '/api/save').as('saveRequest');");
    expect(built!.specCode).toContain("cy.fixture('sample.json');");
  });

  it('writes the generated spec + commands files into the real cypress/ project', () => {
    const built = buildSpec(exportedDashboardFlow(), undefined, getDefaultReusableFlows())!;

    mkdirSync(dirname(GENERATED_SPEC_PATH), { recursive: true });
    const specFile =
      "// AUTO-GENERATED by src/engine/exportedSpecFixture.test.ts — do not edit by hand.\n" +
      "import '../../support/generated-commands';\n\n" +
      `${built.specCode}\n`;
    writeFileSync(GENERATED_SPEC_PATH, specFile, 'utf8');

    mkdirSync(dirname(GENERATED_COMMANDS_PATH), { recursive: true });
    const commandsFile =
      '// AUTO-GENERATED by src/engine/exportedSpecFixture.test.ts — do not edit by hand.\n' +
      // A `declare global` augmentation is only legal inside an external module
      // (a file with its own import/export) — see cypress/support/commands.ts's
      // own trailing `export {};` for the same reason. Without this, `tsc`
      // treats the file as a global script and reports a *new*, unmerged,
      // non-generic `Chainable` instead of augmenting the real ambient one.
      `${built.commandTypesCode}\n\n${built.commandsCode}\n\nexport {};\n`;
    writeFileSync(GENERATED_COMMANDS_PATH, commandsFile, 'utf8');
  });
});
